### ISSUE TITLE
Integrate development workflow with Prettier

### ISSUE THREAD

**Issue by imballinst** [ans-4175/password-ga#10]
I think integrating Prettier to the repository (particularly to the `devDependencies` in `package.json`) will be useful, because:

1. Contributors who use "Format on save" in their IDE (in my case, Visual Studio Code) will be able to "delegate" the formatting concerns to the machine.
2. In case if a contributor's IDE is not integrated with Prettier, then we can have a GitHub Actions as a "guard". We can do so with `prettier --check` ([--check flag docs](https://prettier.io/docs/en/cli.html#--check)). We will also provide a script, such as below, so that if the GitHub Action fails, they can run this script (so they don't have to update the files manually):

```json
{
  "scripts": {
    "format": "prettier --write src"
  }
}
```

This will enforce a soft consistency on code formatting for all contributors. I usually use this as my default config, but I'm open for changes:

```json
{
  "trailingComma": "none",
  "printWidth": 80,
  "tabWidth": 2,
  "semi": true,
  "singleQuote": true
}
```

## Possible tasks

- Arrive at a decision on which Prettier rules we want to use
- Add Prettier
- Add Prettier script to `package.json`
- Format all files under `src`
- **[Optional]** Add GitHub action for formatting check

**Comment by ans-4175** [comment]
Nice addition for consistencies, I think prettier on github actions would be good.

Regarding rules, any guidelines or standard? Usually I look for [GoogleStandard](https://google.github.io/styleguide/jsguide.html)

But yours rules seems same "style" with me too.

**Comment by ans-4175** [comment]
I assigned this to you @imballinst , maybe you could start "claimed" with draft PR

**Comment by imballinst** [comment]
> Regarding rules, any guidelines or standard? Usually I look for [GoogleStandard](https://google.github.io/styleguide/jsguide.html)

@ans-4175 yes, that seems like a very comprehensive guide. For React codebases, I think it's a bit more lenient. Some React codebases use all lowercase for files/folders, e.g. Chakra UI https://github.com/chakra-ui/chakra-ui/tree/main/packages/accordion/src, but PascalCase in Material UI https://github.com/mui-org/material-ui/tree/master/packages/mui-material/src/Accordion, so I don't have a strong opinion about it.

> I assigned this to you @imballinst , maybe you could start "claimed" with draft PR

Sure!
